name: Ansible Deploy

on:
  push:
    branches:
      - staging
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    # ðŸ”¹ Map GitHub Environment to branch
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set inventory based on branch
        run: |
          if [ "${GITHUB_REF_NAME}" = "staging" ]; then
            echo "INVENTORY=inventories/staging/hosts.ini" >> $GITHUB_ENV
          elif [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "INVENTORY=inventories/production/hosts.ini" >> $GITHUB_ENV
          else
            echo "Unsupported branch"
            exit 1
          fi

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Verify files exist (debug step)
        run: |
          pwd
          ls -la
          ls -la inventories/
          ls -la inventories/staging || true
          ls -la inventories/production || true

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i "$INVENTORY" site.yml
